export default {
  nickname: state => state.nickname,
  hasName: state => state.hasName,
  isNameValid: state => state.isNameValid,
  players: state => state.players,
  isStarted: state => state.isStarted,
  state: state => state.state,
  status: state => state.status,
  time: state => state.time,
  categories: state => state.categories,
  question: state => state.question,
  answer: state => state.answer,
  answers: state => state.answers,
  choices: state => state.choices,
  tempScore: state => state.tempScore,
  score: state => state.score,
  total: state => state.total,
  answerMatrix: state => state.answerMatrix,
  isJoinedRoom: state => state.isJoinedRoom,
  currentPlayerId: state => state.currentPlayerId,
  otherQuestion: state => state.otherQuestion,
  ticks: state => state.ticks,
}